# Generated by Django 5.2 on 2026-07-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0026_llmconfig_model_tier'),
        ('langgraph_integration', '0027_chatsession_resolved_runtime_fields'),
    ]

    operations = [
    ]
