# Generated by Django 5.2 on 2026-09-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0028_merge_20260723_1326'),
        ('langgraph_integration', '0032_chatmessage_unique_session_chat_message'),
    ]

    operations = [
    ]
