# Generated by Django 5.2 on 2026-09-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_environments', '0002_alter_apienvironment_verify_ssl'),
        ('client_certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apienvironment',
            name='client_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_environments', to='client_certificates.clientcertificate', verbose_name='Client Certificate'),
        ),
    ]
