# Generated by Django 5.2 on 2026-09-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0022_merge_20260828_1737'),
        ('ui_automation', '0023_uipagesteps_auth_state'),
    ]

    operations = [
    ]
