# Generated by Django 5.2 on 2026-09-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_certificates', '0001_initial'),
        ('ui_automation', '0024_merge_20260923_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='uienvironmentconfig',
            name='client_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_env_configs', to='client_certificates.clientcertificate', verbose_name='客户端证书'),
        ),
        migrations.AddField(
            model_name='uienvironmentconfig',
            name='ignore_https_errors',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='忽略 HTTPS 证书校验'),
        ),
    ]
