# Generated by Django 5.2 on 2026-09-24 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_management', '0005_alter_filereference_ref_type'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('cert_type', models.CharField(choices=[('pem', 'PEM（证书 + 私钥）'), ('pkcs12', 'PKCS#12（.pfx/.p12）')], default='pem', max_length=20, verbose_name='Certificate Type')),
                ('passphrase_encrypted', models.TextField(blank=True, default='', verbose_name='Encrypted Passphrase')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cert_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file_management.fileasset', verbose_name='Certificate File')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('key_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file_management.fileasset', verbose_name='Private Key File')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_certificates', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Client Certificate',
                'verbose_name_plural': 'Client Certificates',
                'db_table': 'client_certificate',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'project')},
            },
        ),
    ]
